version: '3.9'

services:
  product_db:
    image: postgres:latest
    container_name: product_db
    ports:
      - "5437:5432" 
    environment:
      POSTGRES_DB: product_db
      POSTGRES_USER: product_username
      POSTGRES_PASSWORD: product_password
    volumes:
      - product_db_data:/var/lib/postgres/data

volumes:
  product_db_data: